### ISSUE TITLE
Have a new way of doing variables

### ISSUE THREAD

**Issue by aamrixx** [Malvion/drast#15]
Hello, I have a new way of doing variables that may look nice and more modern and the same is to say about the data types. Also I would like there to be a warning when a variables is undefined. Currently for variables you put the type then the variable name and data. 
```
i8, i16, i32, i64, isize
u8, u16, u32, u64, usize
```
```
Current    :   int test = 123
New        :   var test: i64 = 123 
```

**Comment by Ashwin-Paudel** [comment]
Ok, i’m working on it

**Comment by C-BJ** [comment]
`i8, i16, i32, i64, isize`
`u8, u16, u32, u64, usize`
`f32 f64 ......`

**Comment by Ashwin-Paudel** [comment]
Old syntax
```C++
import io

int :: main() {
  int x = 123
  int y = 321

  print("Y: ", y)
  print("X: ", x) 
}
```
New syntax 
```Swift
import std

func main() : i64 {
  var x: i64 = 123
  var y: i64 = 321
  
  print("Y: {}", y)
  print("X: {}", x)
  return 0
}
```

**Comment by WongMan58** [comment]
Looks great

**Comment by C-BJ** [comment]
If **const** is a constant, **val** can be a variable only can assigned once

**Comment by C-BJ** [comment]
import std

func main() : i32 {
  var x: i32 = 123
  var y: i32 = 321
  val z = x//OK
  z += 1//ERROR
  const C = x//ERROR
  print("Y: {}", y)
  print("X: {}", x)
  return 0
}

**Comment by C-BJ** [comment]
> Old syntax
> 
> ```c++
> import io
> 
> int :: main() {
>   int x = 123
>   int y = 321
> 
>   print("Y: ", y)
>   print("X: ", x) 
> }
> ```
> 
> New syntax
> 
> ```swift
> import std
> 
> func main() : i64 {
>   var x: i64 = 123
>   var y: i64 = 321
>   
>   print("Y: {}", y)
>   print("X: {}", x)
>   return 0
> }
> ```

The main func should return i32 or i64

**Comment by C-BJ** [comment]
We decide to use
`val`= `let` in rust
`var`= `let mut` in rust
`const` = `const` in rust
the idea came from kotlin

**Comment by 0verse** [comment]
have you guys seen how jai or odin declares functions or variables? I think the old way could be more coherent by defining like this:

> 
> i32 main :: () {
>     i64 x :: 123   (constant)
>     i64 y := 321   (variable)
> }

In this way there is no explicit need to declare const, var,  or let mut.

**Comment by Ashwin-Paudel** [comment]
> Have you guys seen how jai or odin declares functions or variables? I think the old syntax could be more coherent by defining like this:
> 
> ```
>  i32 main :: () {
>      i64 x :: 123   (constant)
>      i64 y := 321   (variable)
>  }
> ```
> 
> In this way there is no explicit need to declare const, var, or let mut.

In a text editor, you would type 'var' to find a variable. Finding a variable, as well as functions and constants, will be more harder if you use that syntax, since you would have to look for them manually.

**Comment by yodabyte0** [comment]
> Have you guys seen how jai or odin declares functions or variables? I think the old syntax could be more coherent by defining like this:
> 
>  
> ```
>  i32 main :: () {
>      i64 x :: 123   (constant)
>      i64 y := 321   (variable)
>  }
> ```
> 
> In this way there is no explicit need to declare const, var,  or let mut.

Nice idea

**Comment by Ashwin-Paudel** [comment]
Re-wrote the whole syntax!
