### ISSUE TITLE
Review the simplicity, unity, readability and orthogonality of grammar

### ISSUE THREAD

**Issue by C-BJ** [Malvion/drast#16]
Of course, people who use other languages should be used to reading
After: https://github.com/Malvion/drast/issues/15

**Comment by Ashwin-Paudel** [comment]
## Variables

#### Old
```C
char myVariable = ‘A'
```

#### New
```Swift
var myVariable = ‘A'
```

## Constants

#### New
```Swift
let myVariable = “Hello”
myVariable += “World” // error
```

## Function

#### Old
```C
int :: main() {
```

#### New
```Swift
func main(): i64 {
```

**Comment by C-BJ** [comment]
> # Changes made so far
> ## Variables
> #### Old
> ```c
> char myVariable = ‘A'
> ```
> 
> #### New
> ```swift
> var myVariable = ‘A'
> ```
> 
> ## Constants
> #### New
> ```swift
> let myVariable = “Hello”
> myVariable += “World” // error
> ```
> 
> ## Function
> #### Old
> ```c
> int :: main() {
> ```
> 
> #### New
> ```swift
> func main(): i64 {
> ```

Outdated

**Comment by Ashwin-Paudel** [comment]
#15 Discuss in this issue
